apiVersion: v1
kind: Pod
metadata:
  name: rnachat # you prefered pod name
spec:
  volumes:
    - name: rnachat-data
      persistentVolumeClaim:
        claimName: rnachat-pvc
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 128Gi
  containers:
    - name: vol-container
      image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-devel # I recommend this image or continuumio/miniconda3
      workingDir: /
      command: ["/bin/bash", "-c"]
      args:
        - |
          apt-get update && apt-get install -y git curl python3-pip && \
          pip install gdown && \
          git clone https://github.com/HouZhu2001/RNAChat.git && \
          gdown "https://drive.google.com/uc?export=download&id=1q5r6tFty2vQuDny4NVQqjVMkw5YyXRMn" -O /data/checkpoint_stage1.pth && \
          gdown "https://drive.google.com/uc?export=download&id=1jVHMCbbL236BK7khQ906JSuBNyPwV05o" -O /data/checkpoint_stage2.pth && \
          echo "Repo cloned and checkpoint downloaded!" && \
          cp -r /data/* /RNAChat/rnachat/checkpoints && \
          pip install -r /RNAChat/requirements.txt && \
          git clone https://github.com/lbcb-sci/RiNALMo.git /RNAChat/rnachat/rinalmo && \
          cd /RNAChat/rnachat/rinalmo && \
          pip install . && \
          pip install flash-attn==2.3.2 && \
          cd ../../ && \
          echo "Sleeping for 30 minutes..." && \
          sleep 1800 && \
          python3 train.py && \
          tail -f /dev/null
      resources:
        limits:
          cpu: 4
          nvidia.com/gpu: 1
          memory: 32Gi
      volumeMounts:
        - mountPath: /data
          name: rnachat-data
        - mountPath: /dev/shm # mounted on /dev/shm
          name: dshm
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: Exists
