apiVersion: v1
kind: Pod
metadata:
  name: pod-name # you prefered pod name
spec:
  volumes:
    - name: pvc-name
      persistentVolumeClaim:
        claimName: pvc-name
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  containers:
    - name: vol-container
      image: nvidia/cuda:11.8.0-devel-ubuntu22.04 # I recommend this image or continuumio/miniconda3
      command: ["/bin/bash", "-c"]
      args:
      - |
        apt-get update && apt-get install -y git curl && \
        cd /pvc-name && \
        git clone https://github.com/HouZhu2001/RNAChat.git && \
        curl -L -o /pvc-name/RNAChat/rnachat/checkpoints/checkpoint_stage1.pth "https://docs.google.com/uc?export=download&id=YOUR_FILE_ID" && \
        echo "Repo cloned and checkpoint downloaded!" && \
        tail -f /dev/null
      resources:
        limits:
          cpu: 16
          nvidia.com/gpu: 1
          memory: 32Gi
      volumeMounts:
        - mountPath: /pvc-name
          name: pvc-name
        - mountPath: /dev/shm # mounted on /dev/shm
          name: dshm
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - "GPU-type" # you prefered GPU
