apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rnachat-pvc
  namespace: ecepxie
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs-east
